local M = {}

local colors = require("custom.theme.dark.palette")

M.setup = function()
	return {
		Normal = { fg = colors.noir_3, bg = colors.none },
		NonText = { fg = colors.noir_2, bg = colors.none },
		Comment = { fg = colors.noir_6, italic = true },
		Constant = { fg = colors.noir_2 },
		Title = { fg = colors.text },
		String = { fg = colors.noir_5 },
		Character = { fg = colors.noir_3 },
		Directory = { fg = colors.noir_4 },
		Number = { fg = colors.noir_5 },
		Boolean = { fg = colors.noir_5 },
		Float = { fg = colors.noir_5 },
		Identifier = { fg = colors.noir_2 },
		Function = { fg = colors.noir_2 },
		Statement = { fg = colors.noir_4 },
		Conditional = { fg = colors.noir_4 },
		Repeat = { fg = colors.noir_4 },
		Label = { fg = colors.noir_4 },
		Operator = { fg = colors.noir_5 },
		Keyword = { fg = colors.noir_4 },
		Exception = { fg = colors.red },
		PreProc = { fg = colors.noir_4 },
		Include = { fg = colors.red },
		Define = { fg = colors.noir_4 },
		Macro = { fg = colors.noir_4 },
		PreCondit = { fg = colors.noir_4 },
		Type = { fg = colors.noir_2 },
		StorageClass = { fg = colors.noir_4 },
		Structure = { fg = colors.noir_2 },
		Typedef = { fg = colors.noir_2 },
		Special = { fg = colors.noir_4 },
		SpecialChar = { fg = colors.noir_3 },
		Tag = { fg = colors.noir_4 },
		Delimiter = { fg = colors.noir_3 },
		SpecialComment = { fg = colors.noir_3 },
		Debug = { fg = colors.red },
		Underlined = { underline = true },
		Error = { fg = colors.red },
		Todo = { fg = colors.teal, bold = true },
		StatusLine = { fg = colors.text, bg = colors.none },
		StatusLineNC = { fg = colors.text, bg = colors.none },
		LineNr = { bg = colors.none, fg = colors.noir_6 },
		Visual = { bg = colors.noir_7 },
		QuickFixLine = { bg = colors.none, fg = colors.text },

		["@variable"] = { fg = colors.noir_1 },
		["@variable.builtin"] = { fg = colors.noir_1 },
		["@variable.member"] = { fg = colors.noir_2 },
		["@variable.parameter"] = { fg = colors.noir_2, italic = true },

		["@constructor"] = { fg = colors.noir_2 },
		["@lsp.type.parameter"] = { fg = "#999999", italic = true },

		["@type"] = { fg = colors.noir_1 },
		["@type.qualifier"] = { fg = colors.noir_5 },
		["@type.builtin"] = { fg = colors.noir_1 },

		["@keyword"] = { fg = colors.noir_4 },
		["@keyword.modifier"] = { fg = colors.noir_4 },
		["@keyword.preproc"] = { fg = colors.noir_4 },
		["@keyword.namespace"] = { fg = colors.noir_4 },
		["@keyword.type"] = { fg = colors.noir_4 },
		["@keyword.control"] = { fg = colors.noir_4 },
		["@keyword.operator.logical"] = { fg = colors.noir_5 },
		["@keyword.coroutine"] = { fg = colors.noir_4 },
		["@keyword.function"] = { fg = colors.noir_4 },
		["@keyword.operator"] = { fg = colors.noir_4 },
		["@keyword.return"] = { fg = colors.noir_4 },
		["@keyword.conditional"] = { fg = colors.noir_4 },
		["@keyword.repeat"] = { fg = colors.noir_4 },
		["@keyword.import"] = { fg = colors.noir_4 },

		["@function"] = { fg = colors.noir_1 },
		["@function.method"] = { fg = colors.noir_2 },
		["@function.method.call"] = { fg = colors.noir_2 },
		["@function.builtin"] = { fg = colors.noir_4 },
		["@function.call"] = { fg = colors.noir_2 },
		["@function.macro"] = { fg = colors.noir_4 },

		["@method"] = { fg = colors.noir_2 },
		["@method.call"] = { fg = colors.noir_2 },

		["@string"] = { fg = colors.noir_5 },
		["@string.escape"] = { fg = colors.noir_4 },
		["@string.special"] = { fg = colors.noir_4 },

		["@number"] = { fg = colors.noir_5 },
		["@boolean"] = { fg = colors.noir_5 },
		["@constant"] = { fg = colors.noir_1 },
		["@constant.builtin"] = { fg = colors.noir_1 },

		["@operator"] = { fg = colors.noir_5 },
		["@punctuation.bracket"] = { fg = colors.noir_4 },
		["@punctuation.delimiter"] = { fg = colors.noir_4 },
		["@punctuation.special"] = { fg = colors.noir_4 },

		["@tag"] = { fg = colors.noir_4 },
		["@tag.attribute"] = { fg = colors.noir_3 },
		["@tag.delimiter"] = { fg = colors.noir_3 },

		["@property"] = { fg = colors.noir_3 },
		["@field"] = { fg = colors.noir_3 },
		["@parameter"] = { fg = colors.noir_3, italic = true },

		["@namespace"] = { fg = colors.noir_2 },
		["@module"] = { fg = colors.noir_1 },
		["@module.builtin"] = { fg = colors.noir_1 },
		["@label"] = { fg = colors.text },

		Cursor = { bg = colors.none },
		CursorLine = { bg = colors.none, fg = colors.none },
		CursorLineNr = { bg = colors.none, fg = colors.noir_2, bold = true },

		GitSignsAdd = { fg = colors.green, bg = colors.none },
		GitSignsChange = { fg = colors.mauve, bg = colors.none },
		GitSignsDelete = { fg = colors.pink, bg = colors.none },
		GitSignsCurrentLineBlame = { fg = colors.noir_7 },

		TelescopeNormal = { bg = colors.none, fg = colors.noir_5 },
		TelescopeBorder = { bg = colors.none, fg = colors.noir_7 },
		TelescopeMatching = { bg = colors.none, fg = colors.noir_1 },
		TelescopeSelection = { bg = colors.none, fg = colors.noir_1 },
		TelescopeResultsLineNr = { bg = "#181818" },
		TelescopeResultsDiffAdd = { bg = colors.none, fg = colors.green },
		TelescopeResultsDiffChange = { bg = colors.none, fg = colors.yellow },
		TelescopeResultsDiffDelete = { bg = colors.none, fg = colors.red },
		TelescopeResultsDiffUntracked = { bg = colors.none, fg = colors.yellow },

		NvimTreeGitDirty = { fg = colors.noir_1 },
		NvimTreeGitNew = { fg = colors.noir_1 },
		NvimTreeGitStaged = { fg = colors.noir_1 },
		NvimTreeGitUnstaged = { fg = colors.noir_1 },
		NvimTreeGitUntracked = { fg = colors.noir_1 },
		NvimTreeGitRenamed = { fg = colors.noir_1 },
		NvimTreeGitIgnored = { fg = colors.noir_6 },
		NvimTreeGitMerge = { fg = colors.noir_1 },
		NvimTreeGitModified = { fg = colors.noir_1 },
		NvimTreeGitDeleted = { fg = colors.noir_1 },

		NvimTreeWinSeparator = { bg = colors.none, fg = colors.none },
		NvimTreeFolderIcon = { fg = colors.noir_5 },
		NvimTreeFolderName = { fg = colors.noir_4 },
		NvimTreeFileIcon = { fg = colors.noir_5 },
		NvimTreeFileName = { fg = colors.noir_4 },
		NvimTreeExecFile = { fg = colors.noir_4 },
		NvimTreeIndentMarker = { fg = colors.noir_7 },
		NvimTreeNormal = { fg = colors.noir_4 },
		NvimTreeVertSplit = { bg = colors.none, fg = colors.none },
		NvimTreeOpenedFolderIcon = { bg = colors.none, fg = colors.noir_5 },
		NvimTreeOpenedFolderName = { bg = colors.none, fg = colors.noir_4 },
		NvimTreeCursorLine = { bg = colors.noir_8, fg = colors.none },
		NvimTreeEmptyFolderName = { bg = colors.none, fg = colors.noir_4 },

		DevIconDefault = { fg = colors.noir_4 },

		FloatBorder = { bg = colors.none, fg = colors.noir_7 },
		FloatShadow = { bg = colors.none, fg = colors.none },
		FloatShadowThrough = { bg = colors.none, fg = colors.none },

		NormalFloat = { bg = colors.none, fg = colors.noir_4 },

		Folded = { bg = colors.none, fg = colors.noir_7 },

		Pmenu = { bg = colors.none, fg = colors.noir_3 },
		PmenuSel = { bg = colors.noir_8, fg = colors.text },
		PmenuSbar = { bg = colors.none, fg = colors.none },
		PmenuThumb = { bg = colors.none, fg = colors.none },

		NoiceCmdlineIcon = { bg = colors.none, fg = colors.text },
		NoiceCmdlinePopup = { bg = colors.none, fg = colors.noir_3 },
		NoiceCmdlinePopupBorderInput = { bg = colors.none, fg = colors.noir_5 },
		NoiceCmdlinePopupBorder = { bg = colors.none, fg = colors.noir_8 },

		NoiceLspProgressClient = { fg = colors.noir_1 },
		NoiceLspProgressSpinner = { fg = colors.noir_1 },

		DiagnosticSignError = { fg = colors.red },
		DiagnosticSignWarn = { fg = colors.yellow },
		DiagnosticSignInfo = { fg = colors.blue },
		DiagnosticSignHint = { fg = colors.green },

		DiagnosticError = { fg = colors.red },
		DiagnosticWarn = { fg = colors.yellow },
		DiagnosticInfo = { fg = colors.blue },
		DiagnosticHint = { fg = colors.green },

		CmpItemKindFunction = { fg = colors.pink },
		CmpItemKindMethod = { fg = colors.peach },
		CmpItemKindConstant = { fg = colors.rosewater },
		CmpItemKindEnum = { fg = colors.lavender },
		CmpItemKindField = { fg = colors.sky },
		CmpItemKindProperty = { fg = colors.yellow },
		CmpItemKindVariable = { fg = colors.red },
		CmpItemKindSnippet = { fg = colors.maroon },
		CmpItemKindKeyword = { fg = colors.overlay2 },
		CmpItemKindText = { fg = colors.blue },

		IblScope = { fg = colors.noir_7 },

		StatusMode = { fg = colors.text, bg = colors.none },
		StatusBranch = { fg = colors.text, bg = colors.none },
		StatusBranchChanges = { fg = colors.noir_5, bg = colors.none },
		StatusFile = { fg = colors.noir_4, bg = colors.none },
		StatusSaved = { fg = colors.noir_4, bg = colors.none },
		StatusWarnings = { fg = colors.yellow, bg = colors.none },
		StatusErrors = { fg = colors.red, bg = colors.none },
		StatusInfos = { fg = colors.blue, bg = colors.none },
		StatusHints = { fg = colors.green, bg = colors.none },
		StatusSpotify = { fg = colors.noir_2, bg = colors.none },

		BufferLineFill = { fg = colors.noir_4, bg = colors.none },
		BufferLineDuplicate = { fg = colors.noir_4, bg = colors.none, italic = false },
		BufferLineDuplicateSelected = { fg = colors.text, bg = colors.none, italic = false },
		BufferLineDuplicateVisible = { fg = colors.noir_4, bg = colors.none, italic = false },
		BufferLineBackground = { fg = colors.noir_4, bg = colors.none },
		BufferLineCloseButton = { fg = colors.noir_4, bg = colors.none },
		BufferLineBufferSelected = { fg = colors.text, bg = colors.none, bold = false, italic = false },
		BufferLineCloseButtonSelected = { fg = colors.text, bg = colors.none },
		BufferLineBufferVisible = { fg = colors.noir_4, bg = colors.none, bold = false, italic = false },
		BufferLineCloseButtonVisible = { fg = colors.noir_4, bg = colors.none },
		BufferLineOffsetSeparator = { fg = colors.none, bg = colors.none },
		BufferLineIndicatorVisible = { fg = colors.none, bg = colors.none },
		BufferLineIndicatorSelected = { fg = colors.none, bg = colors.none },
		BufferLineModified = { fg = colors.noir_4, bg = colors.none },
		BufferLineModifiedVisible = { fg = colors.noir_4, bg = colors.none },
		BufferLineModifiedSelected = { fg = colors.text, bg = colors.none },
		BufferLineSeparator = { fg = colors.noir_4, bg = colors.none },
		BufferLineSeparatorSelected = { fg = colors.none, bg = colors.none },
		BufferLineSeparatorVisible = { fg = colors.noir_4, bg = colors.none },
		BufferLineTruncMarker = { fg = colors.noir_4, bg = colors.none },
	}
end

return M
