PaletteDark = {
	rosewater = "#f5e0dc",
	flamingo = "#f2cdcd",
	pink = "#f5c2e7",
	mauve = "#cba6f7",
	red = "#f38ba8",
	maroon = "#eba0ac",
	peach = "#fab387",
	yellow = "#f9e2af",
	green = "#a6e3a1",
	green_white = "#b5f4d6",
	teal = "#94e2d5",
	sky = "#89dceb",
	sapphire = "#74c7ec",
	blue = "#89b4fa",
	lavender = "#b4befe",
	cyan = "#04D7D7",
	purple = "#6B50FF",
	text = "#ffffff",
	overlay2 = "#9399b2",
	overlay1 = "#7f849c",
	overlay0 = "#6c7086",
	surface2 = "#585b70",
	surface1 = "#45475a",
	surface0 = "#313244",
	base = "#1e1e2e",
	mantle = "#181825",
	crust = "#11111b",
	noir_0 = "#f1f1f1",
	noir_1 = "#e2e2e2",
	noir_2 = "#777777",
	noir_3 = "#666666",
	noir_4 = "#555555",
	noir_5 = "#444444",
	noir_6 = "#333333",
	noir_7 = "#222222",
	noir_8 = "#181818",
	noir_9 = "#111111",
	none = "NONE",
}

PaletteDarkHighlights = {
	Normal = { fg = PaletteDark.noir_3, bg = PaletteDark.none },
	NonText = { fg = PaletteDark.noir_2, bg = PaletteDark.none },
	Comment = { fg = PaletteDark.noir_5, style = "italic" },
	Constant = { fg = PaletteDark.flamingo },
	Title = { fg = PaletteDark.text },
	String = { fg = PaletteDark.noir_5 },
	Character = { fg = PaletteDark.noir_3 },
	Directory = { fg = PaletteDark.noir_4 },
	Number = { fg = PaletteDark.noir_5 },
	Boolean = { fg = PaletteDark.noir_5 },
	Float = { fg = PaletteDark.noir_5 },
	Identifier = { fg = PaletteDark.noir_2 },
	Function = { fg = PaletteDark.rosewater },
	Statement = { fg = PaletteDark.noir_4 },
	Conditional = { fg = PaletteDark.noir_4 },
	Repeat = { fg = PaletteDark.noir_4 },
	Label = { fg = PaletteDark.noir_4 },
	Operator = { fg = PaletteDark.noir_5 },
	Keyword = { fg = PaletteDark.noir_4 },
	Exception = { fg = PaletteDark.red },
	PreProc = { fg = PaletteDark.noir_4 },
	Include = { fg = PaletteDark.red },
	Define = { fg = PaletteDark.noir_4 },
	Macro = { fg = PaletteDark.noir_4 },
	PreCondit = { fg = PaletteDark.noir_4 },
	Type = { fg = PaletteDark.noir_2 },
	StorageClass = { fg = PaletteDark.noir_4 },
	Structure = { fg = PaletteDark.noir_2 },
	Typedef = { fg = PaletteDark.noir_2 },
	Special = { fg = PaletteDark.noir_4 },
	SpecialChar = { fg = PaletteDark.noir_3 },
	Tag = { fg = PaletteDark.noir_4 },
	Delimiter = { fg = PaletteDark.noir_3 },
	SpecialComment = { fg = PaletteDark.noir_3 },
	Debug = { fg = PaletteDark.red },
	Underlined = { style = "underline" },
	Error = { fg = PaletteDark.red },
	Todo = { fg = PaletteDark.teal, style = "bold" },
	StatusLine = { fg = PaletteDark.text, bg = PaletteDark.none },
	StatusLineNC = { fg = PaletteDark.text, bg = PaletteDark.none },
	LineNr = { bg = PaletteDark.none, fg = PaletteDark.noir_6 },
	Visual = { bg = PaletteDark.noir_8 },

	["@variable"] = { fg = PaletteDark.noir_1 },
	["@variable.builtin"] = { fg = PaletteDark.noir_1 },
	["@variable.member"] = { fg = PaletteDark.noir_3 },

	["@constructor"] = { fg = PaletteDark.noir_2 },
	["@lsp.type.parameter"] = { fg = "#999999", style = "italic" },

	["@type"] = { fg = PaletteDark.noir_1 },
	["@type.qualifier"] = { fg = PaletteDark.noir_6 },
	["@type.builtin"] = { fg = PaletteDark.noir_1 },

	["@keyword"] = { fg = PaletteDark.noir_4 },
	["@keyword.modifier"] = { fg = PaletteDark.noir_6 },
	["@keyword.coroutine"] = { fg = PaletteDark.noir_4 },
	["@keyword.function"] = { fg = PaletteDark.noir_4 },
	["@keyword.operator"] = { fg = PaletteDark.noir_5 },
	["@keyword.return"] = { fg = PaletteDark.noir_4 },
	["@keyword.conditional"] = { fg = PaletteDark.noir_4 },
	["@keyword.repeat"] = { fg = PaletteDark.noir_4 },
	["@keyword.import"] = { fg = PaletteDark.noir_4 },

	["@function"] = { fg = PaletteDark.rosewater },
	["@function.builtin"] = { fg = PaletteDark.rosewater },
	["@function.call"] = { fg = PaletteDark.rosewater },
	["@function.macro"] = { fg = PaletteDark.noir_4 },

	["@method"] = { fg = PaletteDark.rosewater },
	["@method.call"] = { fg = PaletteDark.rosewater },

	["@string"] = { fg = PaletteDark.noir_5 },
	["@string.escape"] = { fg = PaletteDark.flamingo },
	["@string.special"] = { fg = PaletteDark.flamingo },

	["@number"] = { fg = PaletteDark.noir_5 },
	["@boolean"] = { fg = PaletteDark.noir_5 },
	["@constant"] = { fg = PaletteDark.flamingo },
	["@constant.builtin"] = { fg = PaletteDark.flamingo },

	["@operator"] = { fg = PaletteDark.noir_5 },
	["@punctuation.bracket"] = { fg = PaletteDark.noir_3 },
	["@punctuation.delimiter"] = { fg = PaletteDark.noir_3 },
	["@punctuation.special"] = { fg = PaletteDark.noir_4 },

	["@tag"] = { fg = PaletteDark.noir_4 },
	["@tag.attribute"] = { fg = PaletteDark.noir_3 },
	["@tag.delimiter"] = { fg = PaletteDark.noir_3 },

	["@property"] = { fg = PaletteDark.noir_3 },
	["@field"] = { fg = PaletteDark.noir_3 },
	["@parameter"] = { fg = PaletteDark.noir_3, style = "italic" },

	["@namespace"] = { fg = PaletteDark.noir_2 },
	["@module"] = { fg = PaletteDark.noir_1 },
	["@label"] = { fg = PaletteDark.noir_4 },

	Cursor = { bg = PaletteDark.none },
	CursorLine = { bg = PaletteDark.none, fg = PaletteDark.none },
	CursorLineNr = { bg = PaletteDark.none, fg = PaletteDark.noir_2, style = "bold" },

	GitSignsAdd = { fg = PaletteDark.green_white, bg = PaletteDark.none },
	GitSignsChange = { fg = PaletteDark.rosewater, bg = PaletteDark.none },
	GitSignsDelete = { fg = PaletteDark.pink, bg = PaletteDark.none },
	GitSignsCurrentLineBlame = { fg = PaletteDark.noir_7 },

	TelescopeNormal = { bg = PaletteDark.none, fg = PaletteDark.noir_4 },
	TelescopeBorder = { bg = PaletteDark.none, fg = PaletteDark.noir_8 },
	TelescopeMatching = { bg = PaletteDark.none, fg = PaletteDark.noir_1 },
	TelescopeSelection = { bg = PaletteDark.none, fg = PaletteDark.noir_2, style = "bold" },
	TelescopeResultsLineNr = { bg = "#181818" },
	TelescopeResultsDiffAdd = { bg = PaletteDark.none, fg = PaletteDark.green },
	TelescopeResultsDiffChange = { bg = PaletteDark.none, fg = PaletteDark.yellow },
	TelescopeResultsDiffDelete = { bg = PaletteDark.none, fg = PaletteDark.red },
	TelescopeResultsDiffUntracked = { bg = PaletteDark.none, fg = PaletteDark.yellow },

	NvimTreeGitDirty = { fg = PaletteDark.rosewater },
	NvimTreeGitNew = { fg = PaletteDark.green_white },
	NvimTreeGitStaged = { fg = PaletteDark.noir_0 },
	NvimTreeGitUnstaged = { fg = PaletteDark.noir_4 },
	NvimTreeGitUntracked = { fg = PaletteDark.noir_2 },
	NvimTreeGitRenamed = { fg = PaletteDark.noir_1 },
	NvimTreeGitIgnored = { fg = PaletteDark.noir_7 },
	NvimTreeGitMerge = { fg = PaletteDark.noir_1 },
	NvimTreeGitModified = { fg = PaletteDark.rosewater },
	NvimTreeGitDeleted = { fg = PaletteDark.pink },

	NvimTreeWinSeparator = { bg = PaletteDark.none, fg = PaletteDark.none },
	NvimTreeFolderIcon = { fg = PaletteDark.noir_4 },
	NvimTreeFolderName = { fg = PaletteDark.noir_4 },
	NvimTreeFileIcon = { fg = PaletteDark.noir_4 },
	NvimTreeFileName = { fg = PaletteDark.noir_4 },
	NvimTreeExecFile = { fg = PaletteDark.noir_4 },
	NvimTreeIndentMarker = { fg = PaletteDark.noir_8 },
	NvimTreeNormal = { fg = PaletteDark.noir_4 },
	NvimTreeVertSplit = { bg = PaletteDark.none, fg = PaletteDark.none },
	NvimTreeOpenedFolderIcon = { bg = PaletteDark.none, fg = PaletteDark.noir_4 },
	NvimTreeOpenedFolderName = { bg = PaletteDark.none, fg = PaletteDark.noir_4 },
	NvimTreeCursorLine = { bg = "#181818", fg = PaletteDark.none },
	NvimTreeEmptyFolderName = { bg = PaletteDark.none, fg = PaletteDark.noir_4 },

	DevIconDefault = { fg = PaletteDark.noir_4 },

	FloatBorder = { bg = PaletteDark.none, fg = PaletteDark.noir_8 },
	FloatShadow = { bg = PaletteDark.none, fg = PaletteDark.none },
	FloatShadowThrough = { bg = PaletteDark.none, fg = PaletteDark.none },

	NormalFloat = { bg = PaletteDark.none, fg = PaletteDark.noir_4 },

	Folded = { bg = PaletteDark.none, fg = PaletteDark.noir_7 },

	Pmenu = { bg = "#181818", fg = PaletteDark.noir_3 },
	PmenuSel = { bg = PaletteDark.noir_8, fg = PaletteDark.text },
	PmenuSbar = { bg = "#181818", fg = PaletteDark.none },
	PmenuThumb = { bg = PaletteDark.noir_8, fg = PaletteDark.none },

	NoiceCmdlineIcon = { bg = PaletteDark.none, fg = PaletteDark.text },
	NoiceCmdlinePopup = { bg = PaletteDark.none, fg = PaletteDark.noir_3 },
	NoiceCmdlinePopupBorderInput = { bg = PaletteDark.none, fg = PaletteDark.noir_5 },
	NoiceCmdlinePopupBorder = { bg = PaletteDark.none, fg = PaletteDark.noir_8 },

	NoiceLspProgressClient = { fg = PaletteDark.noir_0 },
	NoiceLspProgressSpinner = { fg = PaletteDark.noir_0 },

	DiagnosticSignError = { fg = PaletteDark.red },
	DiagnosticSignWarn = { fg = PaletteDark.yellow },
	DiagnosticSignInfo = { fg = PaletteDark.blue },
	DiagnosticSignHint = { fg = PaletteDark.green },

	DiagnosticError = { fg = PaletteDark.red },
	DiagnosticWarn = { fg = PaletteDark.yellow },
	DiagnosticInfo = { fg = PaletteDark.blue },
	DiagnosticHint = { fg = PaletteDark.green },

	CmpItemKindFunction = { fg = PaletteDark.pink },
	CmpItemKindMethod = { fg = PaletteDark.peach },
	CmpItemKindConstant = { fg = PaletteDark.rosewater },
	CmpItemKindEnum = { fg = PaletteDark.lavender },
	CmpItemKindField = { fg = PaletteDark.sky },
	CmpItemKindProperty = { fg = PaletteDark.yellow },
	CmpItemKindVariable = { fg = PaletteDark.red },
	CmpItemKindSnippet = { fg = PaletteDark.maroon },
	CmpItemKindKeyword = { fg = PaletteDark.overlay2 },
	CmpItemKindText = { fg = PaletteDark.blue },

	IndentBlanklineChar = { fg = PaletteDark.mantle },
	IndentBlanklineSpaceChar = { fg = PaletteDark.mantle },
	IndentBlanklineSpaceCharBlankline = { fg = PaletteDark.mantle },
	IndentBlanklineContextChar = { fg = PaletteDark.noir_7 },
}
