PaletteLight = {
	rosewater = "#dc8a78",
	flamingo = "#dd7878",
	pink = "#ea76cb",
	mauve = "#8839ef",
	red = "#d20f39",
	maroon = "#e64553",
	peach = "#fe640b",
	yellow = "#df8e1d",
	green = "#40a02b",
	teal = "#179299",
	sky = "#04a5e5",
	sapphire = "#209fb5",
	blue = "#1e66f5",
	lavender = "#7287fd",
	cyan = "#04A5A5",
	purple = "#5835D1",
	text = "#000000",

	overlay0 = "#9ca0b0",
	overlay1 = "#8c8fa1",
	overlay2 = "#7c7f93",

	surface2 = "#acb0be",
	surface1 = "#bcc0cc",
	surface0 = "#ccd0da",

	base = "#eff1f5",
	mantle = "#e6e9ef",
	crust = "#dce0e8",

	noir_0 = "#252525",
	noir_1 = "#383838",
	noir_2 = "#4b4b4b",
	noir_3 = "#5e5e5e",
	noir_4 = "#717171",
	noir_5 = "#888888",
	noir_6 = "#9f9f9f",
	noir_7 = "#b3b3b3",
	noir_8 = "#d0d0d0",
	noir_9 = "#e0e0e0",

	none = "NONE",
}

PaletteLightHighlights = {
	Normal = { fg = PaletteLight.noir_3, bg = PaletteLight.none },
	NonText = { fg = PaletteLight.noir_6, bg = PaletteLight.none },
	Comment = { fg = PaletteLight.noir_7, style = "italic" },
	Constant = { fg = PaletteLight.noir_2 },
	Title = { fg = PaletteLight.text },
	String = { fg = PaletteLight.noir_5 },
	Character = { fg = PaletteLight.noir_5 },
	Directory = { fg = PaletteLight.noir_1 },
	Number = { fg = PaletteLight.noir_5 },
	Boolean = { fg = PaletteLight.noir_5 },
	Float = { fg = PaletteLight.noir_5 },
	Identifier = { fg = PaletteLight.noir_3 },
	Function = { fg = PaletteLight.noir_1 },
	Statement = { fg = PaletteLight.noir_1 },
	Conditional = { fg = PaletteLight.noir_1 },
	Repeat = { fg = PaletteLight.noir_1 },
	Label = { fg = PaletteLight.noir_2 },
	Operator = { fg = PaletteLight.noir_5 },
	Keyword = { fg = PaletteLight.noir_1 },
	Exception = { fg = PaletteLight.red },
	PreProc = { fg = PaletteLight.noir_2 },
	Include = { fg = PaletteLight.noir_2 },
	Define = { fg = PaletteLight.noir_2 },
	Macro = { fg = PaletteLight.noir_2 },
	PreCondit = { fg = PaletteLight.noir_2 },
	Type = { fg = PaletteLight.noir_1 },
	StorageClass = { fg = PaletteLight.noir_1 },
	Structure = { fg = PaletteLight.noir_1 },
	Typedef = { fg = PaletteLight.noir_1 },
	Special = { fg = PaletteLight.noir_4 },
	SpecialChar = { fg = PaletteLight.noir_3 },
	Tag = { fg = PaletteLight.noir_2 },
	Delimiter = { fg = PaletteLight.noir_5 },
	SpecialComment = { fg = PaletteLight.noir_6 },
	Debug = { fg = PaletteLight.red },
	Underlined = { style = "underline" },
	Error = { fg = PaletteLight.red },
	Todo = { fg = PaletteLight.teal, style = "bold" },
	StatusLine = { fg = PaletteLight.text, bg = PaletteLight.none },
	StatusLineNC = { fg = PaletteLight.text, bg = PaletteLight.none },
	LineNr = { bg = PaletteLight.none, fg = PaletteLight.noir_6 },
	Visual = { bg = PaletteLight.noir_9 },

	["@variable"] = { fg = PaletteLight.noir_4 },
	["@variable.builtin"] = { fg = PaletteLight.noir_4 },
	["@variable.member"] = { fg = PaletteLight.noir_3 },
	["@variable.parameter"] = { fg = PaletteLight.noir_4, style = "italic" },

	["@constant"] = { fg = PaletteLight.noir_4 },
	["@constant.builtin"] = { fg = PaletteLight.noir_4 },

	["@constructor"] = { fg = PaletteLight.noir_2 },
	["@lsp.type.parameter"] = { fg = PaletteLight.noir_4, style = "italic" },

	["@type"] = { fg = PaletteLight.noir_2 },
	["@type.builtin"] = { fg = PaletteLight.noir_2 },
	["@type.qualifier"] = { fg = PaletteLight.noir_1 },

	["@operator"] = { fg = PaletteLight.noir_1 },

	["@keyword"] = { fg = PaletteLight.noir_1 },
	["@keyword.conditional"] = { fg = PaletteLight.noir_1 },
	["@keyword.function"] = { fg = PaletteLight.noir_1 },
	["@keyword.return"] = { fg = PaletteLight.noir_1 },
	["@keyword.operator"] = { fg = PaletteLight.noir_1 },
	["@keyword.coroutine"] = { fg = PaletteLight.noir_3 },
	["@keyword.modifier"] = { fg = PaletteLight.noir_1 },
	["@keyword.import"] = { fg = PaletteLight.noir_1 },
	["@keyword.type"] = { fg = PaletteLight.noir_1 },
	["@keyword.exception"] = { fg = PaletteLight.noir_1 },

	["@punctuation.bracket"] = { fg = PaletteLight.noir_4 },
	["@punctuation.delimiter"] = { fg = PaletteLight.noir_4 },

	["@function"] = { fg = PaletteLight.noir_4 },
	["@function.builtin"] = { fg = PaletteLight.noir_0 },
	["@function.method"] = { fg = PaletteLight.noir_4 },
	["@function.call"] = { fg = PaletteLight.noir_1 },
	["@function.method.call"] = { fg = PaletteLight.noir_1 },

	["@property"] = { fg = PaletteLight.noir_4 },
	["@field"] = { fg = PaletteLight.noir_3 },

	["@namespace"] = { fg = PaletteLight.noir_2 },
	["@module"] = { fg = PaletteLight.noir_2 },
	["@label"] = { fg = PaletteDark.noir_9 },

	["@tag"] = { fg = PaletteLight.noir_1 },

	Cursor = { bg = PaletteLight.none },
	CursorLine = { bg = PaletteLight.none, fg = PaletteLight.none },
	CursorLineNr = { bg = PaletteLight.none, fg = PaletteLight.noir_1, style = "bold" },

	GitSignsAdd = { fg = PaletteLight.green, bg = PaletteLight.none },
	GitSignsChange = { fg = PaletteLight.rosewater, bg = PaletteLight.none },
	GitSignsDelete = { fg = PaletteLight.red, bg = PaletteLight.none },
	GitSignsCurrentLineBlame = { fg = PaletteLight.noir_7 },

	TelescopeNormal = { bg = PaletteLight.none, fg = PaletteLight.noir_6 },
	TelescopeBorder = { bg = PaletteLight.none, fg = PaletteLight.noir_8 },
	TelescopeMatching = { bg = PaletteLight.none, fg = PaletteLight.noir_2 },
	TelescopeSelection = { bg = PaletteLight.none, fg = PaletteLight.noir_2 },
	TelescopeResultsLineNr = { bg = PaletteLight.base },
	TelescopeResultsDiffAdd = { bg = PaletteLight.none, fg = PaletteLight.green },
	TelescopeResultsDiffChange = { bg = PaletteLight.none, fg = PaletteLight.yellow },
	TelescopeResultsDiffDelete = { bg = PaletteLight.none, fg = PaletteLight.red },
	TelescopeResultsDiffUntracked = { bg = PaletteLight.none, fg = PaletteLight.yellow },

	IblScope = { fg = PaletteLight.noir_8 },

	NvimTreeGitDirty = { fg = PaletteLight.noir_0 },
	NvimTreeGitNew = { fg = PaletteLight.noir_0 },
	NvimTreeGitStaged = { fg = PaletteLight.noir_0 },
	NvimTreeGitUnstaged = { fg = PaletteLight.noir_0 },
	NvimTreeGitUntracked = { fg = PaletteLight.noir_0 },
	NvimTreeGitRenamed = { fg = PaletteLight.noir_0 },
	NvimTreeGitIgnored = { fg = PaletteLight.noir_7 },
	NvimTreeGitMerge = { fg = PaletteLight.noir_0 },
	NvimTreeGitModified = { fg = PaletteLight.noir_0 },
	NvimTreeGitDeleted = { fg = PaletteLight.noir_0 },

	NvimTreeWinSeparator = { bg = PaletteLight.none, fg = PaletteLight.none },
	NvimTreeFolderIcon = { fg = PaletteLight.noir_4 },
	NvimTreeFolderName = { fg = PaletteLight.noir_4 },
	NvimTreeFileIcon = { fg = PaletteLight.noir_4 },
	NvimTreeFileName = { fg = PaletteLight.noir_4 },
	NvimTreeExecFile = { fg = PaletteLight.noir_4 },
	NvimTreeIndentMarker = { fg = PaletteLight.noir_8 },
	NvimTreeNormal = { fg = PaletteLight.noir_4 },
	NvimTreeVertSplit = { bg = PaletteLight.none, fg = PaletteLight.none },
	NvimTreeOpenedFolderIcon = { bg = PaletteLight.none, fg = PaletteLight.noir_4 },
	NvimTreeOpenedFolderName = { bg = PaletteLight.none, fg = PaletteLight.noir_4 },
	NvimTreeCursorLine = { bg = PaletteLight.base, fg = PaletteLight.none },
	NvimTreeEmptyFolderName = { bg = PaletteLight.none, fg = PaletteLight.noir_4 },

	DevIconDefault = { fg = PaletteLight.noir_4 },

	FloatBorder = { bg = PaletteLight.none, fg = PaletteLight.noir_8 },
	FloatShadow = { bg = PaletteLight.none, fg = PaletteLight.none },
	FloatShadowThrough = { bg = PaletteLight.none, fg = PaletteLight.none },

	NormalFloat = { bg = PaletteLight.none, fg = PaletteLight.noir_4 },

	Folded = { bg = PaletteLight.none, fg = PaletteLight.noir_7 },

	Pmenu = { bg = PaletteLight.none, fg = PaletteLight.noir_3 },
	PmenuSel = { bg = PaletteLight.noir_8, fg = PaletteLight.text },
	PmenuSbar = { bg = PaletteLight.none, fg = PaletteLight.none },
	PmenuThumb = { bg = PaletteLight.none, fg = PaletteLight.none },

	NoiceCmdlineIcon = { bg = PaletteLight.none, fg = PaletteLight.text },
	NoiceCmdlinePopup = { bg = PaletteLight.none, fg = PaletteLight.noir_3 },
	NoiceCmdlinePopupBorderInput = { bg = PaletteLight.none, fg = PaletteLight.noir_5 },
	NoiceCmdlinePopupBorder = { bg = PaletteLight.none, fg = PaletteLight.noir_8 },

	NoiceLspProgressClient = { fg = PaletteLight.noir_0 },
	NoiceLspProgressSpinner = { fg = PaletteLight.noir_0 },

	DiagnosticSignError = { fg = PaletteLight.red },
	DiagnosticSignWarn = { fg = PaletteLight.yellow },
	DiagnosticSignInfo = { fg = PaletteLight.blue },
	DiagnosticSignHint = { fg = PaletteLight.green },

	DiagnosticError = { fg = PaletteLight.red },
	DiagnosticWarn = { fg = PaletteLight.yellow },
	DiagnosticInfo = { fg = PaletteLight.blue },
	DiagnosticHint = { fg = PaletteLight.green },

	CmpItemKindFunction = { fg = PaletteLight.pink },
	CmpItemKindMethod = { fg = PaletteLight.peach },
	CmpItemKindConstant = { fg = PaletteLight.rosewater },
	CmpItemKindEnum = { fg = PaletteLight.lavender },
	CmpItemKindField = { fg = PaletteLight.sky },
	CmpItemKindProperty = { fg = PaletteLight.yellow },
	CmpItemKindVariable = { fg = PaletteLight.red },
	CmpItemKindSnippet = { fg = PaletteLight.maroon },
	CmpItemKindKeyword = { fg = PaletteLight.overlay2 },
	CmpItemKindText = { fg = PaletteLight.blue },

	StatusMode = { fg = PaletteLight.noir_0, bg = PaletteLight.none },
	StatusBranch = { fg = PaletteLight.noir_1, bg = PaletteLight.none },
	StatusBranchChanges = { fg = PaletteLight.noir_4, bg = PaletteLight.none },
	StatusFile = { fg = PaletteLight.noir_6, bg = PaletteLight.none },
	StatusSaved = { fg = PaletteLight.noir_6, bg = PaletteLight.none },
	StatusWarnings = { fg = PaletteLight.yellow, bg = PaletteLight.none },
	StatusErrors = { fg = PaletteLight.red, bg = PaletteLight.none },
	StatusInfos = { fg = PaletteLight.blue, bg = PaletteLight.none },
	StatusHints = { fg = PaletteLight.green, bg = PaletteLight.none },
	StatusSpotify = { fg = PaletteLight.noir_5, bg = PaletteLight.none },
}
